// Copyright (c) 2011 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// This file is automatically generated by GRIT.  Do not edit.

#include "grit/ui_resources_standard_map.h"

#include "base/basictypes.h"
#include "grit/ui_resources_standard.h"

const GritResourceMap kUiResourcesStandard[] = {
  {"IDR_BUBBLE_B", IDR_BUBBLE_B},
  {"IDR_BUBBLE_BL", IDR_BUBBLE_BL},
  {"IDR_BUBBLE_BR", IDR_BUBBLE_BR},
  {"IDR_BUBBLE_B_ARROW", IDR_BUBBLE_B_ARROW},
  {"IDR_BUBBLE_L", IDR_BUBBLE_L},
  {"IDR_BUBBLE_L_ARROW", IDR_BUBBLE_L_ARROW},
  {"IDR_BUBBLE_R", IDR_BUBBLE_R},
  {"IDR_BUBBLE_R_ARROW", IDR_BUBBLE_R_ARROW},
  {"IDR_BUBBLE_T", IDR_BUBBLE_T},
  {"IDR_BUBBLE_TL", IDR_BUBBLE_TL},
  {"IDR_BUBBLE_TR", IDR_BUBBLE_TR},
  {"IDR_BUBBLE_T_ARROW", IDR_BUBBLE_T_ARROW},
};

const size_t kUiResourcesStandardSize = arraysize(kUiResourcesStandard);
