// Copyright (c) Google Inc. 2011
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.

#pragma once

#define IDR_BUBBLE_B 24000
#define IDR_BUBBLE_BL 24001
#define IDR_BUBBLE_BR 24002
#define IDR_BUBBLE_B_ARROW 24003
#define IDR_BUBBLE_L 24004
#define IDR_BUBBLE_L_ARROW 24005
#define IDR_BUBBLE_R 24006
#define IDR_BUBBLE_R_ARROW 24007
#define IDR_BUBBLE_T 24008
#define IDR_BUBBLE_TL 24009
#define IDR_BUBBLE_TR 24010
#define IDR_BUBBLE_T_ARROW 24011
