// Copyright (c) Google Inc. 2011
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.

#pragma once

#define IDS_UI_FONT_FAMILY 7500
#define IDS_UI_FONT_FAMILY_XP 7501
#define IDS_UI_FONT_SIZE_SCALER 7502
#define IDS_UI_FONT_SIZE_SCALER_XP 7503
#define IDS_MINIMUM_UI_FONT_SIZE 7504
